apiVersion: apps/v1
kind: Deployment
metadata:
  name:  sandbox-deployment
  labels:
    name:  sandbox-deployment
spec:
  replicas:  2
  selector:
    matchLabels:
      app:  sandbox
  template:
    metadata:
      labels:
        app: sandbox
    spec:
      containers:
      - image:  sandbox:latest
        name:  sandbox
        resources:
          requests:
            cpu: "300m"
            memory: "128M"
          limits:
            cpu: "600m"
            memory: "256M"
        livenessProbe:
          httpGet:
            path: /api/sandbox/health
            port: 3000
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/sandbox/health
            port: 3000
          initialDelaySeconds: 30
          timeoutSeconds: 10
        env:
        - name:  S3_BUCKET
          value:  cohort-capstone-329599656829-ap-southeast-1-an       
        ports:
        - containerPort:  3000
          name:  sandbox