services:
  backend:
    build: ./Backend
    ports:
      - "3000:3000"
    volumes:
      - ./Backend:/app
      - Backend_node_modules:/app/node_modules
    command: npx nodemon -L server.js

  frontend:
    build: ./Frontend
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend:/app
      - Frontend_node_modules:/app/node_modules
    command: npm run dev -- --host

volumes:
  Backend_node_modules:
  Frontend_node_modules: