apiVersion: skaffold/v4beta13
kind: Config

metadata:
  name: mern-app

build:
  local:
    push: false

  artifacts:
    - image: core
      context: backend
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: /app
          - src: '**/*.json'
            dest: /app

manifests:
  rawYaml:
    - k8s/core-deployment.yml
    - k8s/core-service.yml
    - k8s/core-ingress.yml

portForward:
  - resourceType: service
    resourceName: core-service
    port: 80
    localPort: 3000